export const tasksData = [
  {
    id: 1,
    title: "Create a Responsive Landing Page",
    body: "Design and code a responsive landing page for a new product launch. Ensure it looks great on desktop and mobile devices.",
    priority: "High",
    dueDate: "2023-11-15",
    completed: true,
  },
  // {
  //   id: 2,
  //   title: "Implement a Navigation Menu",
  //   body: "Add a navigation menu to the website that includes links to various sections of the site. Make it user-friendly and visually appealing.",
  //   priority: "Medium",
  //   dueDate: "2023-11-22",
  //   completed: false,
  // },
  // {
  //   id: 3,
  //   title: "Optimize Page Load Times",
  //   body: "Optimize the website's performance by reducing page load times. Minimize HTTP requests, compress images, and use lazy loading where appropriate.",
  //   priority: "High",
  //   dueDate: "2023-11-18",
  //   completed: false,
  // },
  // {
  //   id: 4,
  //   title: "Integrate with APIs",
  //   body: "Integrate data from external APIs to display dynamic content on the website. Ensure proper error handling and data fetching techniques.",
  //   priority: "High",
  //   dueDate: "2023-11-25",
  //   completed: false,
  // },
  // {
  //   id: 5,
  //   title: "Cross-Browser Testing",
  //   body: "Test the website on multiple web browsers (e.g., Chrome, Firefox, Safari, Edge) to ensure compatibility and a consistent user experience.",
  //   priority: "Medium",
  //   dueDate: "2023-11-19",
  //   completed: false,
  // },
  // {
  //   id: 6,
  //   title: "Accessibility Compliance",
  //   body: "Ensure the website is accessible to all users, including those with disabilities. Implement ARIA roles, alt text for images, and keyboard navigation.",
  //   priority: "High",
  //   dueDate: "2023-11-24",
  //   completed: false,
  // },
  // {
  //   id: 7,
  //   title: "UI/UX Enhancements",
  //   body: "Collaborate with designers to improve the user interface and user experience of the website. Implement animations, micro-interactions, and other enhancements.",
  //   priority: "Medium",
  //   dueDate: "2023-11-28",
  //   completed: false,
  // },
  // {
  //   id: 8,
  //   title: "Version Control with Git",
  //   body: "Use Git for version control to track code changes, collaborate with team members, and maintain a clean and organized codebase.",
  //   priority: "Low",
  //   dueDate: "2023-11-30",
  //   completed: false,
  // },
];
